---
title: "Goals and Impacts"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

# Introduction
*Describe briefly the rationale of your project, you overall objectives and potential impacts.*

## Brief Rationales

As per now, university students struggle every semester to create a timetable. In fact, there are many possible combinations of classes that would meet the criterion of their studies. But how to visualize all that satisfy the time constraints (impossible to follow two classes taking place at the same time), the modules ones (specific to each university curriculum) and total ECTS constraints (on average 30 ECTS credits must be completed) easily ? The current solution most students follow is based on trial and error, but it result is somehow inefficient: as soon as a first suitable schedule is found, the student stops searching, even if he/she could have been happier with possible another timetable not discovered. 

## Overall Objectives

The objective is to design an optimization algorithm that would generate all possible timetables from a choice of possible classes. From our perspective of Master students in Management at HEC Lausanne, following the track "Business Analytics", we face every semester the following challenge, in the sense that we must choose classes that account for 3 constraints: 
- the **time constraints** (overlapping classes on the schedule are impossible to take), 
- the **"Modules" ECTS constraints** (classes are either in *Business Analytics* or *Electives*), 
- the **total ECTS credits constraints** (do more than *X* ECTS credits for each semester). 

## Potential Impacts

While we first aim to focus on creating a optimization tool for Business Analytics students at HEC Lausanne, this algorithm could be easily scaled up to be used with other orientations for instance. 
If successful, we can imagine that the HEC administration could offer such solutions to its students.
