---
title: "Goals and Impacts"
output: html_notebook
editor_options: 
  markdown: 
    wrap: 72
runtime: shiny
---

```{r, warning=FALSE}
source(here::here("scripts/setup.R"))
```

```{r, warning=FALSE}
# Replication with 55 times the hours slots for the first and last 7 weeks 
weeks <- rep(1,  55)

# Replication 5 times all the hours slots from 8 to 19
hours_of_day <- rep(9:19, 5)

# Replicate 11 times Monday (1), Tuesday, Wednesday, Thursday and Friday (5)
days_of_week <-c(rep(1, 11), rep(2, 11), rep(3, 11), rep(4, 11), rep(5, 11))

# Create a list with all conditions for hours, day and first/last weeks combinations
cols_to_make_first <- rlang::parse_exprs(
  paste0('ifelse(
         First ==', weeks, 
         '& End >=', hours_of_day,
         '& Start <', hours_of_day,
         '& Day ==', days_of_week,',1,0)'))

cols_to_make_last <- rlang::parse_exprs(
  paste0('ifelse(
         Last ==', weeks, 
         '& End >=', hours_of_day,
         '& Start <', hours_of_day,
         '& Day ==', days_of_week,',1,0)'))
```

# All semesters
```{r}
# Obtain the information about classes in each semester 
raw_input <- list()
for (i in 1:3){
  df <- read_excel(here::here("data/Timetable_Master_Management.xlsx"), sheet=1) %>%
  mutate(Start_nice = chron::times(gsub("1899-12-31 ", "", as.character(Start_nice))), 
         End_nice = chron::times(gsub("1899-12-31 ", "", as.character(End_nice))), 
         Day = recode_factor(Day,
          "Monday" = 1,
          "Tuesday" = 2,
          "Wednesday" = 3,
          "Thursday" = 4,
          "Friday"= 5),
         First = `First 7 Weeks`, 
         Last = `Last 7 Weeks`, 
         MANDATORY = `Mandatory BA`,
         CORE = `BA orientation`, 
         CORE_credits = CORE*Credits,  
         ELECTIVE = ifelse(CORE == 1, 0, 1), 
         ELECTIVE_credits = ELECTIVE * Credits, 
         Moment = as.factor(paste0(
           Day, "_", as.factor(ifelse(End <= 12, "AM", "PM"))))) %>%
  filter(Semester == i) %>%
  select(-`BA orientation`, -`Mandatory BA`,
         -Semester, -`Last 7 Weeks`, -`First 7 Weeks`) 
  
  raw_input[[i]] <- df
}

################################################################################

# Create a vector of mandatory classes for each semester
classes_mandatory <- list()
for (i in 1:3){
  df <- raw_input[[i]] %>% 
  group_by(Class) %>% 
  filter(MANDATORY==1) %>% 
  select(Class) %>% unique() %>% unlist()
  
  classes_mandatory[[i]] <- df
}

################################################################################

# Remove the variable Mandatory for the HEC_sem[i]_BA
for (i in 1:3) {
  df <- raw_input[[i]] %>% select(-MANDATORY)
  raw_input[[i]] <- df
}

################################################################################

# Create dummies for all hours slots for first seven weeks
part_1 <- list()
for (i in 1:3) {
  df_1 <- raw_input[[i]] %>% 
    rowwise(.) %>%
    mutate(!!!cols_to_make_first)  %>%
    ungroup %>% 
    pivot_longer(cols=starts_with("ifelse(F")) 
  part_1[[i]] <- df_1
}

rm(df_1)
################################################################################

# Create dummies for all hours slots for last seven weeks
part_2 <- list()
for (i in 1:3) {
  df_2 <- raw_input[[i]] %>% 
    rowwise(.) %>%
    mutate(!!!cols_to_make_first)  %>%
    ungroup %>% 
    pivot_longer(cols=starts_with("ifelse(F")) 
  part_2[[i]] <- df_2
}

rm(df_2)
################################################################################

# Merge info of the two above tables, generate dummies for Moment
HEC_dummies_BA <- list()
for (i in 1:3) {
  df <-  rbind(part_1[[i]], part_2[[i]]) %>%
    filter(value>0) %>% 
    select(-value) %>%
    fastDummies::dummy_cols(., c("Moment", "name")) %>%
    select(-Moment, -Start_nice, -End_nice, -Moment, -name, 
         -Start, -End, -Day, -CORE, -Professor, -Last, -First, -ELECTIVE)
  HEC_dummies_BA[[i]] <- df
}

################################################################################

# Remove unnecessary files created for hours slots dummies
rm(part_1, part_2)
rm(df)
################################################################################

# Store the names of the classes for each semester
unique <- list()
for (i in 1:3){
  unique[[i]] <- HEC_dummies_BA[[i]]$Class
}

################################################################################

# Generate dummies for classes (to be able to select classes)
for (i in 1:3){
  HEC_dummies_BA[[i]] <- HEC_dummies_BA[[i]] %>%
    fastDummies::dummy_cols(., c("Class")) %>% 
  select(-Class) %>% t() %>% as.data.frame()
}

################################################################################

# Rename the columns with the unique_[i] names stored before
for (i in 1:3){
  colnames(HEC_dummies_BA[[i]]) <- unique[[i]]
}

################################################################################

# Store the names of all constraints
constraints <- list()
for (i in 1:3){
  const <- row.names(HEC_dummies_BA[[i]])
  constraints[[i]] <-  const
}

rm(const)
################################################################################

# Keep only one columns for each classes (and not all of them when duplicated)
for (i in 1:3){
HEC_dummies_BA[[i]] <- data.frame(sapply(split(1:ncol(HEC_dummies_BA[[i]]), 
                                  colnames(HEC_dummies_BA[[i]])), 
                      function(j) do.call(pmax, HEC_dummies_BA[[i]][j])))
}

################################################################################

# Rename rows with constraints stored before
for (i in 1:3){
  row.names(HEC_dummies_BA[[i]]) <- constraints[[i]]
}

################################################################################

# Rename columns with classes names (and remove the word "Class" before)
for (i in 1:3){
  colnames(HEC_dummies_BA[[i]]) <- row.names(HEC_dummies_BA[[i]] %>%
   filter(grepl("Class_", rownames(HEC_dummies_BA[[i]]))))
  
  colnames(HEC_dummies_BA[[i]]) <- gsub("Class_","",colnames(HEC_dummies_BA[[i]]))
}

################################################################################

# Store all classes for semester 1 to be displayed in the scrolling list
classes_semester <- list()
for (i in 1:3){
  classes_semester[[i]] <- colnames(HEC_dummies_BA[[i]])
}

################################################################################

# Create a vector to be able to retrieve the Shiny reactive of classes
classes_constraints <- list()
for (i in 1:3){
  classes_constraints[[i]] <- vector(length = length(classes_semester[[i]]))
}

################################################################################

# Store all moments for semester 1 to be displayed in the scrolling list
moments_semester <- list()
for (i in 1:3){
  moments_semester[[i]] <- levels(raw_input[[i]]$Moment) 
  moments_semester[[i]] <- sub("1_","Monday ", moments_semester[[i]])
  moments_semester[[i]] <- sub("2_","Tuesday ", moments_semester[[i]])
  moments_semester[[i]] <- sub("3_","Wednesday ", moments_semester[[i]])
  moments_semester[[i]] <- sub("4_","Thursday ", moments_semester[[i]])
  moments_semester[[i]] <- sub("5_","Friday ", moments_semester[[i]])
}

################################################################################

# Create a vector to be able to retrieve the Shiny reactive of moments
moments_constraints <- list()
for (i in 1:3){
  moments_constraints[[i]] <- vector(length = length(moments_semester[[i]]))
}

################################################################################
```


```{r, warning=FALSE, error=FALSE}
ui <- navbarPage(theme = shinytheme("cerulean"),
  "HEC Lausanne - Timetable suggestions for Management students",
  helpText("If no timetable is displayed, try to relax some constraints.
           Don't take too many credits per semester, a standard load is 30.
           Make sure to have over semester 2 & 3 at least 36 core credits."),
  tabPanel(
    "Semester 1",
    sidebarPanel(
      # ECTS choices
      sliderInput(
        inputId = "credits_1",
        min = 0,
        max = 42,
        value = 30,
        label = "Total credits"),
      sliderInput(
        inputId = "CORE_credits_1",
        min = 0,
        max = 36,
        value = 18,
        label = "Mandatory credits"),
      sliderInput(
        inputId = "ELECTIVE_credits_1",
        min = 0,
        max = 24,
        value = 12,
        label = "Elective credits"),
      #Classes choices
      pickerInput(
        inputId = "Classes_1",
        label = "Classes:",
        choices = classes_semester[[1]],
        selected = classes_mandatory[[1]], # Refer to mandatory classes
        options = list(
          `actions-box` = TRUE, size = 10,
          `selected-text-format` = "count > 3"),
        multiple = TRUE),
      # Moments choices
      pickerInput(
        inputId = "Moments_1",
        label = "Day - AM/PM:",
        choices = moments_semester[[1]],
        selected = moments_semester[[1]],
        options = list(
          `actions-box` = TRUE, size = 10,
          `selected-text-format` = "count > 3"),
        multiple = TRUE)),
    # Show a plot of the generated distribution
    mainPanel(mainPanel(tabsetPanel(type = "tabs",
                  tabPanel("Visual Timetable", plotOutput("timetable_1_graph")),
                  tabPanel("More detailed Timetable", tableOutput("timetable_1"))), style='width: 900px'))),
  

  tabPanel(
    "Semester 2",
   sidebarPanel(
     # ECTS choices
      sliderInput(inputId = "credits_2",
        min = 0, max = 42, value = 30, label = "Total credits"),
      sliderInput(inputId = "CORE_credits_2",
        min = 0, max = 36, value = 12, label = "Mandatory credits"),
      sliderInput(inputId = "ELECTIVE_credits_2",
        min = 0, max = 24, value = 18, label = "Elective credits"),
    #Classes choices
      pickerInput(
        inputId = "Classes_2",
        label = "Classes:",
        choices = classes_semester[[2]],
        selected = classes_mandatory[[2]],
        options = list(
          `actions-box` = TRUE, size = 10,
          `selected-text-format` = "count > 3"),
        multiple = TRUE),
      # Moments choices
      pickerInput(
        inputId = "Moments_2",
        label = "Day - AM/PM:",
        choices = moments_semester[[2]],
        selected = moments_semester[[2]],
        options = list(
          `actions-box` = TRUE, size = 10,
          `selected-text-format` = "count > 3"),
        multiple = TRUE)),
    # Show a plot of the generated distribution
    mainPanel(mainPanel(tabsetPanel(type = "tabs",
                  tabPanel("Visual Timetable", plotOutput("timetable_2_graph")),
                  tabPanel("More detailed Timetable", tableOutput("timetable_2"))), style='width: 900px'))),

  tabPanel(
    "Semester 3",
    sidebarPanel(
      # ECTS choices
      sliderInput(inputId = "credits_3",
        min = 0, max = 42, value = 30, label = "Total credits"),
      sliderInput(inputId = "CORE_credits_3",
        min = 0, max = 36, value = 12, label = "Mandatory credits"),
      sliderInput(inputId = "ELECTIVE_credits_3",
        min = 0, max = 24, value = 18, label = "Elective credits"),

      #Classes choices
      pickerInput(
        inputId = "Classes_3",
        label = "Classes:",
        choices = classes_semester[[3]],
        selected = classes_mandatory[[3]],
        options = list(
          `actions-box` = TRUE, size = 10,
          `selected-text-format` = "count > 3"),
        multiple = TRUE),
      # Moments choices
      pickerInput(
        inputId = "Moments_3",
        label = "Day - AM/PM:",
        choices = moments_semester[[3]],
        selected = moments_semester[[3]],
        options = list(
          `actions-box` = TRUE, size = 10,
          `selected-text-format` = "count > 3"),
        multiple = TRUE)),
    # Show a plot of the generated distribution
    mainPanel(mainPanel(tabsetPanel(type = "tabs",
                  tabPanel("Visual Timetable", plotOutput("timetable_3_graph")),
                  tabPanel("More detailed Timetable", tableOutput("timetable_3"))), style='width: 900px'))))
```

```{r, warning=FALSE, error=FALSE}
# Set matrix corresponding to coefficients of constraints
f.con <- list()
for (i in 1:3){
  f.con[[i]] <- HEC_dummies_BA[[i]]
}

# Define parameters
nb_of_moment <- list()
for (i in 1:3){
  nb_of_moment[[i]] <- length(row.names(HEC_dummies_BA[[i]] %>%
  filter(grepl("AM|PM", rownames(HEC_dummies_BA[[i]])))))
}

nb_of_timeslot <- list()
for (i in 1:3){
  nb_of_timeslot[[i]] <- dim(HEC_dummies_BA[[i]] %>%
  filter(grepl("name", rownames(HEC_dummies_BA[[i]]))))[1]
}

nb_of_class <- list()
for (i in 1:3){
  nb_of_class[[i]] <- ncol(HEC_dummies_BA[[i]])
}

# Set coefficients of the objective function (min total credits taken)
f.obj <- list()
for (i in 1:3){
  f.obj[[i]] <- HEC_dummies_BA[[i]][1,] %>% unname() %>% unlist()
}

# Set unequality/equality signs
f.dir <- list()
for (i in 1:3){
  f.dir[[i]] <- c(
    ">=", # Credits constraint
    ">=", # CORE Credits constraint
    ">=", # ELECTIVE Credits constraint
    rep("<=", nb_of_moment[[i]]), # Chunk of the day
    rep.int("<=", nb_of_timeslot[[i]]), # Time constraints
    rep(">=", nb_of_class[[i]]))
}

nice_input <- list()
for (i in 1:3){
  nice_input[[i]] <- raw_input[[i]]%>%
      mutate(
        Start = as.character(Start_nice),
        End = as.character(End_nice),
        Day = recode_factor(Day,
          `1` = "Monday",
          `2` = "Tuesday",
          `3` = "Wednesday",
          `4` = "Thursday",
          `5` = "Friday"),
        Core = recode(CORE,
          `1` = "Yes",
          `0` = "No")
      )  %>% 
      select(Day, Start, End, Class, Credits, Professor, Core) %>%
      arrange(Day, Start)
}
```

```{r, warning=FALSE, error=FALSE}
server <- function(input, output, session) {
  
  
  output$timetable_1 <- renderTable({
  # Period of the day
  Moments_1 <- reactive(input$Moments_1)
  for (i in 1:length(moments_semester[[1]])) {
    moments_constraints[[1]][i] <-
      moments_semester[[1]][i] %in% Moments_1()
  }
  
  Classes_1 <- reactive(input$Classes_1)
  for (i in 1:length(classes_semester[[1]])) {
    classes_constraints[[1]][i] <-
      classes_semester[[1]][i] %in%  Classes_1()
  }
  
  # Set right hand side coefficients
  f.rhs_1 <- c(
    reactive(input$credits_1)(),    # Credits constraint
    reactive(input$CORE_credits_1)(), # CORE Credits constraint
    reactive(input$ELECTIVE_credits_1)(), # ELECTIVE Credits constraint
    length(classes_constraints[[1]])*moments_constraints[[1]], # Chunk of the day constraints
    rep.int(1, nb_of_timeslot[[1]]), # Time constraints
    classes_constraints[[1]]) # Classes constraints  
    
  # Variables choices (1 if class is taken, 0 otherwise)
  timetable_1 <- cbind(as.numeric(
            lp("min", f.obj[[1]], f.con[[1]], f.dir[[1]], 
               f.rhs_1, all.bin = TRUE, presolve = 1)$solution),
                       colnames(HEC_dummies_BA[[1]])) %>%
      as.data.frame() %>%
      mutate(Choice = V1, Class = V2) %>%
      left_join(nice_input[[1]]) %>%
      filter(Choice == 1) %>%
      select(-V1, -V2, -Choice)
  })
  
  output$timetable_1_graph <- renderPlot({
  # Period of the day
  Moments_1 <- reactive(input$Moments_1)
  for (i in 1:length(moments_semester[[1]])) {
    moments_constraints[[1]][i] <- moments_semester[[1]][i] %in%  Moments_1()
  }

  Classes_1 <- reactive(input$Classes_1)
  for (i in 1:length(classes_semester[[1]])) {
    classes_constraints[[1]][i] <- classes_semester[[1]][i] %in% Classes_1()
  }

    # Set right hand side coefficients
  f.rhs_1 <- c(
    reactive(input$credits_1)(),    # Credits constraint
    reactive(input$CORE_credits_1)(), # CORE Credits constraint
    reactive(input$ELECTIVE_credits_1)(), # ELECTIVE Credits constraint
    length(classes_constraints[[1]])*moments_constraints[[1]], # Chunk of the day constraints
    rep.int(1, nb_of_timeslot[[1]]), # Time constraints
    classes_constraints[[1]]) # Classes constraints

    # Variables choices (1 if class is taken, 0 otherwise)
 cbind(
    as.numeric(lp("min",
      f.obj[[1]],
      f.con[[1]],
      f.dir[[1]],
      f.rhs_1,
      all.bin = TRUE,
      presolve = 1)$solution),
  colnames(HEC_dummies_BA[[1]])) %>%
    as.data.frame() %>%
    mutate(Choice = V1, Class = V2) %>%
    left_join(raw_input[[1]]) %>%
    filter(Choice == 1) %>%
    select(-V1,-V2,-Choice) %>%
    transmute(
      x1 = as.numeric(Day) - 0.5,
      x2 = as.numeric(Day) + 0.5,
      y1 = Start,
      y2 = End,
      t = CORE,
      r = Class) %>%
    ggplot() +
    geom_rect(
      mapping = aes(
        xmin = x1,
        xmax = x2,
        ymin = y1,
        ymax = y2,
        fill = r),
      color = "black",
      size = 0,
      alpha = 0.5)  +
    labs(x = "", y = "Hours") +
    scale_x_discrete(limits = c("Monday", "Tuesday", "Wednesday", "Thusrday", "Friday")) +
    scale_y_continuous(breaks = seq(8, 19, by = 1), trans = scales::reverse_trans()) +
    geom_label(aes(
      x = x1 + (x2 - x1) / 2,
      y = y1 + (y2 - y1) / 2,
      label = r),
    size = 2) +
    theme(legend.position = "none") +
    theme(axis.ticks = element_blank())
  })

  output$timetable_2 <- renderTable({

  # Period of the day
  Moments_2 <- reactive(input$Moments_2)
  for (i in 1:length(moments_semester[[2]])) {
    moments_constraints[[2]][i] <- moments_semester[[2]][i] %in%  Moments_2()
  }

  Classes_2 <- reactive(input$Classes_2)
  for (i in 1:length(classes_semester[[2]])) {
    classes_constraints[[2]][i] <- classes_semester[[2]][i] %in%  Classes_2()
  }

    # Set right hand side coefficients
  f.rhs_2 <- c(
    reactive(input$credits_2)(),    # Credits constraint
    reactive(input$CORE_credits_2)(), # CORE Credits constraint
    reactive(input$ELECTIVE_credits_2)(), # ELECTIVE Credits constraint
    length(classes_constraints[[2]])*moments_constraints[[2]], # Chunk of the day constraints
    rep.int(1, nb_of_timeslot[[2]]), # Time constraints
    classes_constraints[[2]]) # Classes constraints

    # Variables choices (1 if class is taken, 0 otherwise)
    timetable_2 <- cbind(as.numeric(
            lp("min", f.obj[[2]], f.con[[2]], f.dir[[2]], 
               f.rhs_2, all.bin = TRUE, presolve = 1)$solution),
                       colnames(HEC_dummies_BA[[2]])) %>%
      as.data.frame() %>%
      mutate(Choice = V1, Class = V2) %>%
      left_join(nice_input[[2]]) %>%
      filter(Choice == 1) %>%
      select(-V1, -V2, -Choice)
  })
  
  output$timetable_2_graph <- renderPlot({
  # Period of the day
  Moments_2 <- reactive(input$Moments_2)
  for (i in 1:length(moments_semester[[2]])) {
    moments_constraints[[2]][i] <- moments_semester[[2]][i] %in%  Moments_2()
  }

  Classes_2 <- reactive(input$Classes_2)
  for (i in 1:length(classes_semester[[2]])) {
    classes_constraints[[2]][i] <- classes_semester[[2]][i] %in% Classes_2()
  }

    # Set right hand side coefficients
  f.rhs_2 <- c(
    reactive(input$credits_2)(),    # Credits constraint
    reactive(input$CORE_credits_2)(), # CORE Credits constraint
    reactive(input$ELECTIVE_credits_2)(), # ELECTIVE Credits constraint
    length(classes_constraints[[2]])*moments_constraints[[2]], # Chunk of the day constraints
    rep.int(1, nb_of_timeslot[[2]]), # Time constraints
    classes_constraints[[2]]) # Classes constraints

    # Variables choices (1 if class is taken, 0 otherwise)
 cbind(
    as.numeric(lp("min",
      f.obj[[2]],
      f.con[[2]],
      f.dir[[2]],
      f.rhs_2,
      all.bin = TRUE,
      presolve = 1)$solution),
  colnames(HEC_dummies_BA[[2]])) %>%
    as.data.frame() %>%
    mutate(Choice = V1, Class = V2) %>%
    left_join(raw_input[[2]]) %>%
    filter(Choice == 1) %>%
    select(-V1,-V2,-Choice) %>%
    transmute(
      x1 = as.numeric(Day) - 0.5,
      x2 = as.numeric(Day) + 0.5,
      y1 = Start,
      y2 = End,
      t = CORE,
      r = Class) %>%
    ggplot() +
    geom_rect(
      mapping = aes(
        xmin = x1,
        xmax = x2,
        ymin = y1,
        ymax = y2,
        fill = r),
      color = "black",
      size = 0,
      alpha = 0.5)  +
    labs(x = "", y = "Hours") +
    scale_x_discrete(limits = c("Monday", "Tuesday", "Wednesday", "Thusrday", "Friday")) +
    scale_y_continuous(breaks = seq(8, 19, by = 1), trans = scales::reverse_trans()) +
    geom_label(aes(
      x = x1 + (x2 - x1) / 2,
      y = y1 + (y2 - y1) / 2,
      label = r),
    size = 2) +
    theme(legend.position = "none") +
    theme(axis.ticks = element_blank())
  })

  output$timetable_3 <- renderTable({
  # Period of the day
  Moments_3 <- reactive(input$Moments_3)
  for (i in 1:length(moments_semester[[3]])) {
    moments_constraints[[3]][i] <- moments_semester[[3]][i] %in%  Moments_3()
  }
  
  Classes_3 <- reactive(input$Classes_3)
  for (i in 1:length(classes_semester[[3]])) {
    classes_constraints[[3]][i] <- classes_semester[[3]][i] %in% Classes_3()
  }
  
    # Set right hand side coefficients
  f.rhs_3 <- c(
    reactive(input$credits_3)(),    # Credits constraint
    reactive(input$CORE_credits_3)(), # CORE Credits constraint
    reactive(input$ELECTIVE_credits_3)(), # ELECTIVE Credits constraint
    length(classes_constraints[[3]])*moments_constraints[[3]], # Chunk of the day constraints
    rep.int(1, nb_of_timeslot[[3]]), # Time constraints
    classes_constraints[[3]]) # Classes constraints

    # Variables choices (1 if class is taken, 0 otherwise)
  timetable_3 <- cbind(as.numeric(
            lp("min", f.obj[[3]], f.con[[3]], f.dir[[3]], 
               f.rhs_3, all.bin = TRUE, presolve = 1)$solution),
                       colnames(HEC_dummies_BA[[3]])) %>%
      as.data.frame() %>%
      mutate(Choice = V1, Class = V2) %>%
      left_join(nice_input[[3]]) %>%
      filter(Choice == 1) %>%
      select(-V1, -V2, -Choice)

  })
  
  output$timetable_3_graph <- renderPlot({
  # Period of the day
  Moments_3 <- reactive(input$Moments_3)
  for (i in 1:length(moments_semester[[3]])) {
    moments_constraints[[3]][i] <- moments_semester[[3]][i] %in%  Moments_3()
  }

  Classes_3 <- reactive(input$Classes_3)
  for (i in 1:length(classes_semester[[3]])) {
    classes_constraints[[3]][i] <- classes_semester[[3]][i] %in% Classes_3()
  }

    # Set right hand side coefficients
  f.rhs_3 <- c(
    reactive(input$credits_3)(),    # Credits constraint
    reactive(input$CORE_credits_3)(), # CORE Credits constraint
    reactive(input$ELECTIVE_credits_3)(), # ELECTIVE Credits constraint
    length(classes_constraints[[3]])*moments_constraints[[3]], # Chunk of the day constraints
    rep.int(1, nb_of_timeslot[[3]]), # Time constraints
    classes_constraints[[3]]) # Classes constraints

    # Variables choices (1 if class is taken, 0 otherwise)
 cbind(
    as.numeric(lp("min",
      f.obj[[3]],
      f.con[[3]],
      f.dir[[3]],
      f.rhs_3,
      all.bin = TRUE,
      presolve = 1)$solution),
  colnames(HEC_dummies_BA[[3]])) %>%
    as.data.frame() %>%
    mutate(Choice = V1, Class = V2) %>%
    left_join(raw_input[[3]]) %>%
    filter(Choice == 1) %>%
    select(-V1,-V2,-Choice) %>%
    transmute(
      x1 = as.numeric(Day) - 0.5,
      x2 = as.numeric(Day) + 0.5,
      y1 = Start,
      y2 = End,
      t = CORE,
      r = Class) %>%
    ggplot() +
    geom_rect(
      mapping = aes(
        xmin = x1,
        xmax = x2,
        ymin = y1,
        ymax = y2,
        fill = r),
      color = "black",
      size = 0,
      alpha = 0.5)  +
    labs(x = "", y = "Hours") +
    scale_x_discrete(limits = c("Monday", "Tuesday", "Wednesday", "Thusrday", "Friday")) +
    scale_y_continuous(breaks = seq(8, 19, by = 1), trans = scales::reverse_trans()) +
    geom_label(aes(
      x = x1 + (x2 - x1) / 2,
      y = y1 + (y2 - y1) / 2,
      label = r),
    size = 2) +
    theme(legend.position = "none") +
    theme(axis.ticks = element_blank())
  })
}
```

```{r}
shinyApp(ui, server)
```
