---
title: "Understanding the app"
author: "Group 2"
date: 2021-12-15T21:13:14-05:00
categories: ["R"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Semesters' choice

There are three tabs, for the three semesters of classes of the Master.\
You can navigate across them by simply clicking on it at the top of the page.

# Initial timetable suggestion

To display an initial timetable, click on "Suggest" on the sidebar panel.

You have the choice to either view, by moving across tabs in the main panel:

-   two visual representations of the selected classes (half-semester classes):

    -   one for the first seven weeks of the semester

    -   one for the last seven weeks of the semester

-   a textual summary of the selected classes

Note that the mandatory classes of this master are pre-selected and will be included in the suggested timetable even if de-selected them from the list of preferred classes.

# User's preferences

You can of course also input your preferences to have a personalized timetable:

-   how many credits you want to do in the Business Analytics track (core credits) ?

-   how many credits you want to do as elective classes (non mandatory ones) ?

-   which half-days you want to have class ?

# Issues

Note that if no timetable is displayed, it simply mean your preferences could not be satisfied. \
In this case, you need to either choose more days and remove conflicting classes.

A good advice is always to start from the first generated timetable.\
Otherwise, to only add a few favorite classes and then scale it up.
