---
title: "Plan"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

# Plan

## Approach and Specific Objectives

As we all come from different universities and countries, it is
interesting to see how each one of them works regarding timetable
creation for classes. We can cite, for instance, Tecnológico de
Monterrey, which is one of our team mates former university. It offers a
software which, according to the courses a student has chosen, displays
in green and blue how some courses overlap, as well as some information
in red also about the course availability. While this is useful for
students, it still takes a while to get a "doable" timetable, so we want
to tackle this problem.

As previously explained, the goal of this project is to create an
algorithm that would generate all possible timetables from a choice of
possible classes. Focusing on the specific case of the Master in
Management at HEC Lausanne, and especially on the track of "Business
Analytics", the project would take into account specifically:

-   the **time constraints** (clashing classes on the schedule are
    impossible to take),

-   the **"modules" ECTS constraints** (classes are either in *Business
    Analytics* or *Electives*),

-   the **total ECTS credits constraints** (do more than *X* ECTS
    credits for each semester).

What is more, it should offer the possibility to users to also
pre-select some classes they are sure to take, as well as how many ECTS
credits in total they need, and the relative allocation between their
main track and the count of Electives. Otherwise, we could also imagine
suggesting timetables only based on the user preferences.

### Potential Extensions

As an extension, the program could also consider more than one semester,
as students generally need to achieve Module ECTS constraints over
Semester 2 and Semester 3. While this optimization tool is aimed first
for Business Analytics students at HEC Lausanne, if successful, it could
be scaled up to be used with other orientations. The ultimate goal would
be that HEC would offer it to its students.

## Data collection

To obtain the data, we will simply copy paste the timetable from the HEC
website, following the following link:
<https://hecnet.unil.ch/hec/timetables/snc_de_pub?pub_id=20491&dyn_lang=fr>.

We could also imagine to web-scrap the data directly from the web, to
fully automate the process.

We will then clean it and add manually the information about the
"Modules" (BA, Marketing, SOL, BEE).

As per now, one of the risks we can present is that the timetable is in
constant change. For instance, for the semester Autumn 2021, the correct
timetable with all the correct courses that were to be imparted was
lastly modified even during the semester. This is a risk that is not in
our hands. Definitely this is something that the university should start
to work on.

Out of that, we don't see the data collection as very problematic,
except maybe for the automation. We should also taken into account that
when the syllabus is updated, data should be recollected.

## Methods and Alternatives

We will rely on Integer Linear Programming, possibly using packages such
as `lpSolve` or `ompr`, as well as `fastDummies`, to create dummy
variables. Overall, we aim to solve the following models:

-   **variables to optimize**: dummy (1= taking, 0= not taking) for each
    class

-   **objective function**: minimize the credits to be done each
    semester

-   **constraints**:

    -   time: two classes can't be taken at the same time (defined time
        slot of 60 minutes)

    -   modules ECTS: *X* credits must be achieved in BA, *Y* credits
        must be achieved with Electives

    -   total ECTS: *Z* credits must be achieved at least

While it seems simple, we need to account for the overlapping classes
(such as classes from 8-10 on Monday can't be combined with classes from
8-12 on Monday), so we need specific modeling. Further, we will allow the user 
to input his/her specific requirements (e.g. free on Monday, 12 credits in BA 
and 15 in Elective, total credits only 27) via the implementation of the Shiny app.

In case we are unsuccessful with the Integer Optimization, we could
still generate randomly many combinations of classes, and then check to
see if such combinations meet the requirements of students, as well as
the time constraints (with a matrix of "overlapping" classes). In this
way, we have an alternative to Integer Linear Programming.
